# Generated by Django 3.2.12 on 2023-06-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Courtwear', 'Courtwear'), ('Accessories', 'Accessories'), ('Ceremonial', 'Ceremonial'), ('Women', 'Women')], default='Accessories', max_length=20),
        ),
    ]
