# Generated by Django 3.1.12 on 2023-06-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherimages',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Women', 'Women'), ('Courtwear', 'Courtwear'), ('Ceremonial', 'Ceremonial'), ('Accessories', 'Accessories'), ('Men', 'Men')], default='Accessories', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='size',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
